### PR TITLE
Added color overlay toggle for dashboard cards

### PR DESCRIPTION
**Pull request by tibogeeraerts**
When I changed the image of a dashboard card to a custom image. It always had a color overlay, so I tried to fix it.

### CODE REVIEW

**Comment by ksucpea** [comment]
First of all, I'd just like to say it's pretty cool that you got everything correct when adding the new feature. I've been working on a new update that would change your code slightly, however. Also, I think I know a more efficient way to remove the overlay. I can update the repo with the new update and you can adjust it if you'd like, so that you are listed as a contributor? I could also add your edits to my version and push the update later. Just let me know what you'd like to do. Thanks

**Comment by tibogeeraerts** [comment]
Thanks for the feedback. I would really appreciate it if I could join the list of contributors. You can choose when to update, to me it can be in the next update when you are done with everything.

**Comment by ksucpea** [comment]
I just updated the repo but it doesn't have any of your changes except you'll see the part where I tested your toggle with my version. Feel free to open another merge or edit this one. I think all you really have to do is change the local storage to sync storage.

**Comment by tibogeeraerts** [comment]
This is my first commit from my repo to another local so I don't really understand it. I hope this solved the issue?

**Comment by ksucpea** [comment]
I'm not really too sure how this works either, but it seems like if I merged it, it would delete everything from the new update. Can you try adding your code to the most recent version of the repo instead?

**Pull request closed without merging**
